# Setup
title:        Structured Learning
tagline:      A project that covers all of the basic data structures
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Damien Nagle
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
